name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v5
      - name: Tests with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: "Install dependencies"
        run: "npm ci"
      # TODO: add prettier
      - name: "Test"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: "npm run lint && npm run typecheck && npm run build"
